sudo: required
services:
        - docker
before_install:
        - wget -qO- https://toolbelt.heroku.com/install.sh | sh
        - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com      
        - docker build -t bidego/docker-react:0.0.1 -f Dockerfile.dev .
        - docker tag bidego/docker-react:0.0.1
          registry.heroku.com/$HEROKU_APP_NAME/web
script:
        - docker run -e CI=true bidego/docker-react:0.0.1 npm run test
deploy:
        provider: script
        script:
                docker push bidego/docker-react:0.0.1;
                docker push registry.heroku.com/$HEROKU_APP_NAME/web;
                heroku container:release web --app $HEROKU_APP_NAME
        on:
                branch: master
