sudo: required
services:
        - docker
before_install:
        - docker build -t bidego/docker-react -f Dockerfile.dev .
script:
        - docker run bidego/docker-react npm run test -- --coverage

