sudo: required
services:
        - docker
before_install:
        - wget -qO- https://toolbelt.heroku.com/install.sh | sh
        - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com      
        - docker build -t bidego/docker-react
          registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.dev .
script:
        - docker run -e CI=true bidego/docker-react npm run test
deploy:
        provider: script
        script:
                docker push bidego/docker-react;
                docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        on:
                branch: master
